#!/usr/bin/env bash

echo "== delete objects"


# check-for-bucket-name
BUCKET_NAME="$1"

if [ -z "$BUCKET_NAME" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# This command creates a json object which contains all the objects in s3 bucket.
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME --query 'Contents[].Key' \
| jq -n '{Objects : [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

# This command delets the objects of s3 bucket with the help of json file
aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json