#!/usr/bin/env bash

echo "== list buckets"

# https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html

aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse |.[0:5] | .[].Name'