#!/usr/bin/env bash
echo "SYNC"

# check for bucket name 
BUCKET_NAME="$1"

if [ -z "$BUCKET_NAME" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

FILE_NAME_PREFIX="$2"

if [ -z "$FILE_NAME_PREFIX" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# lets create output folder
OUTPUT_DIR="/tmp/S3-bash-scripts"

sudo rm -r $OUTPUT_DIR

mkdir -p $OUTPUT_DIR
chmod 755 /tmp/S3-bash-scripts


#Generate a Random number to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for((i =1;i<=$NUM_FILES;i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILE_NAME_PREFIX}_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done


tree $OUTPUT_DIR
# https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files